# -*- coding: utf-8 -*-
"""Test 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hQZGUgcl6Clg9mu1TGFmeKFprZx1oHc
"""

#Đây là phương trình tính quãng đường đi được của chuyển động với vận tốc ban đầu v và bỏ qua lực cản
print("nhap van toc v ban dau: ")
v = float(input())
print("nhap thoi gian bay t: ")
t = float(input())
g = 10
print("gia toc g = ", g)
y = v * t - g*t*t/2

print("y = ", float(abs(y)))
